### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Eden333** [SpaceAfterYou/soulworker-items-viewer#1]
Hi, I wondered if you may need the new KR files to update the site, or did you just not have the time to do so.

**Comment by sawich** [comment]
> Hi, I wondered if you may need the new KR files to update the site, or did you just not have the time to do so.

Yahallo. Haven't kr client. If you send it for me, i'll update site.

**Comment by Eden333** [comment]
> > Hi, I wondered if you may need the new KR files to update the site, or did you just not have the time to do so.
> 
> Yahallo. Haven't kr client. If you send it for me, i'll update site.

which files do you require?
I assume you're on the bsw discord?

**Comment by sawich** [comment]
> which files do you require?

idk. If game no change structure.

- datas/data12.v
- datas/data16.v

> I assume you're on the bsw discord?

Yes. **sawich#1816**
And on bottom of site i drop my discord channel. If you want... >^)))<～～

**Comment by sawich** [comment]
> idk. If game no change structure.

and if password's didn't changed

**Comment by Eden333** [comment]
> > idk. If game no change structure.
> 
> and if password's didn't changed

they did change at somepoint recently.
https://drive.google.com/file/d/1vbyRmi25xZPDpRen7G27ytOvbAsY_U97/view?usp=sharing
I included the Base.dll

**Comment by sawich** [comment]
> I included the Base.dll

can't extract password from this dll

**Comment by Eden333** [comment]
> > I included the Base.dll
> 
> can't extract password from this dll

They have updated their on the 27.01.2021, but still the passwords were visible.
It seems they finally encrypted them OR stored them somewhere else.

**Comment by sawich** [comment]
Updated
